name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Lint Tool
        run: pip install flake8

      - name: Run Lint
        run: flake8 .

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Docker Image
        run: docker build -t gym-app .

      - name: Run Tests in Container
        run: docker run -e PYTHONPATH=/app gym-app pytest

      - name: Run Container
        run: docker run -d -p 5000:5000 gym-app

      - name: Wait for App
        run: sleep 5

      - name: Test App
        run: curl http://localhost:5000

      # 🔹 Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 🔹 Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gym-app:latest .

      # 🔹 Push Docker Image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gym-app:latest

      # 🔹 Setup Kubernetes Config
      - name: Setup Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      # 🔹 Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl rollout restart deployment gym-app
